SET SERVEROUTPUT ON;
DECLARE

cod_cli_pepito NUMBER;
cod_tra_juanito NUMBER;
cod_nota NUMBER;
cod_mantenimiento NUMBER;
cod_sugerencias NUMBER;
cod_horario NUMBER;
cod_factura NUMBER;
cod_guardia NUMBER;
cod_garantia NUMBER;

BEGIN

PRUEBA_CLIENTE.INICIALIZAR;
PRUEBA_TRABAJADOR.INICIALIZAR;
PRUEBA_VALORACIONCLIENTE.INICIALIZAR;
PRUEBA_MANTENIMIENTO.INICIALIZAR;
PRUEBA_SUGERENCIAS.INICIALIZAR;
PRUEBA_HORARIO.INICIALIZAR;
PRUEBA_FACTURA.INICIALIZAR;
PRUEBA_GUARDIA.INICIALIZAR;
PRUEBA_GARANTIA.INICIALIZAR;

--INSERTAR CLIENTE

PRUEBA_CLIENTE.INSERTAR('PRUEBA CLIENTE INSERTAR TODO CORRECTO', 'PEPITO', '21234567T','PALOTES JARA', 'CALLE PARAISO Nº6', '1234b', '662637034', TRUE);
PRUEBA_CLIENTE.INSERTAR('PRUEBA CLIENTE INSERTAR ERRONEO HAY IN NULL', 'PEPITO', '21234587T','PALOTES JARA', NULL, 'CALLE PARAISO Nº6', NULL, FALSE);

--INSERTAR TRABAJADOR


PRUEBA_TRABAJADOR.INSERTAR('PRUEBA TRABAJADOR INSERTAR TRABAJADOR CORRECTO','54762109C', 'JUANITO', 'MARTINEZ ABERRONCHO',
 'CALLE ALFARERIA Nº14', 'juanito@hotmail.com', '1234a', '663587435', TRUE);

PRUEBA_TRABAJADOR.INSERTAR('PRUEBA TRABAJADOR INSERTAR TRABAJADOR ERRONEO HAY UN NULL',NULL, 'JUANITO', 'MARTINEZ ABERRONCHO',
 'CALLE ALFARERIA Nº14', 'juanito@hotmail.com', NULL, '663587435', FALSE);
 
 --INSERTAR VALORACION CLIENTE

PRUEBA_VALORACIONCLIENTE.INSERTAR('PRUEBA VAL CLIENTE INSERTAR CORRECTO', 'TODO CORRECTO', 8,cod_cli_pepito, '01-01-2018', TRUE);

PRUEBA_VALORACIONCLIENTE.INSERTAR('PRUEBA VAL CLIENTE INSERTAR NOTA MAYOR DE 10 ERRONEO', 'TODO CORRECTO', 11,cod_cli_pepito,'01-01-2018', FALSE);

--INSERTAR MANTENIMIENTO

PRUEBA_MANTENIMIENTO.INSERTAR('PRUEBA MANTENIMIENTO INSERTAR CORRECTO','MUY BIEN','20-01-2590', '01-01-2018','NORMAL',
cod_cli_pepito, cod_tra_juanito, TRUE);

PRUEBA_MANTENIMIENTO.INSERTAR('PRUEBA MANTENIMIENTO INSERTAR ERRONEO NULL EN FKidcliente','MUY BIEN','20-01-2019', '01-01-2018','NORMAL',
NULL, NULL, FALSE);

--INSERTAR SUGERENCIA

PRUEBA_SUGERENCIAS.INSERTAR('PRUEBA SUGERENCIAS INSERTAR CORRECTO','MUY BIEN TODO','20-05-2017',cod_tra_juanito,TRUE);

PRUEBA_SUGERENCIAS.INSERTAR('PRUEBA SUGERENCIAS INSERTAR ERRONEO HAY UN NULL','MUY BIEN TODO','20-05-2017',NULL,FALSE);

--INSERTAR HORARIO

PRUEBA_HORARIO.INSERTAR('PRUEBA HORARIO INSERTAR CORRECTO','Lunes','20-01-2019','20-01-2019',cod_tra_juanito,TRUE);

PRUEBA_HORARIO.INSERTAR('PRUEBA HORARIO INSERTAR ERRONEO NO DIA SEMANA','JUNIO','20-01-2019','20-01-2019',cod_tra_juanito,FALSE);

--INSERTAR FACTURA

PRUEBA_FACTURA.INSERTAR('PRUEBA FACTURA INSERTAR CORRECTO', 300,'01-01-2018', 'MUY BIEN', cod_mantenimiento,TRUE);

PRUEBA_FACTURA.INSERTAR('PRUEBA FACTURA INSERTAR ERRONEO HAY UN NULL', 300,'01-01-2018', NULL, cod_mantenimiento,FALSE);

--INSERTAR GARANTIA

PRUEBA_GARANTIA.INSERTAR('PRUEBA GARANTIA INSERTAR CORRECTO', '01-01-2018', '01-01-2020',cod_mantenimiento,TRUE);

PRUEBA_GARANTIA.INSERTAR('PRUEBA GARANTIA INSERTAR ERRONEO HAY UN NULL', NULL, NULL,cod_mantenimiento,FALSE);

--INSERTAR GUARDIA

PRUEBA_GUARDIA.INSERTAR('PRUEBA GUARDIA INSERTAR CORRECTO', 'Jueves', '20-01-2019', '21-01-2019',cod_tra_juanito,TRUE);

PRUEBA_GUARDIA.INSERTAR('PRUEBA GUARDIA INSERTAR ERRONEO DIA MAL', 'Junio', '20-01-2019', '21-01-2019',cod_tra_juanito,FALSE);


--ACTUALIZAR CLIENTE

PRUEBA_CLIENTE.ACTUALIZARDireccion('PRUEBA CLIENTE ACTUALIZAR DIRECCION CORRECTO', cod_cli_pepito, 'CALLE KAMIKAZE Nº20', TRUE);
PRUEBA_CLIENTE.ACTUALIZARTelefono('PRUEBA CLIENTE ACTUALIZAR TELEFONO CORRECTO:', cod_cli_pepito, '662637033', TRUE);
PRUEBA_CLIENTE.ACTUALIZARCONTRA('PRUEBA CLIENTE ACTUALIZAR CONTRA CORRECTO:', cod_cli_pepito, '1234H', TRUE);
 --ACTUALIZAR TRABAJADOR
 
PRUEBA_TRABAJADOR.ACTUALIZARDomicilio('PRUEBA TRABAJADOR ACTUALIZAR DOMICILIO', cod_tra_juanito,'CALLE JABUGO Nº15', TRUE);
PRUEBA_TRABAJADOR.ACTUALIZAREmail('PRUEBA TRABAJADOR ACTUALIZAR EMAIL', cod_tra_juanito,'sintecho@hotmail.com', TRUE);
PRUEBA_TRABAJADOR.ACTUALIZARContra('PRUEBA TRABAJADOR ACTUALIZAR CONTRA', cod_tra_juanito,'1234F', TRUE);

--ACTUALIZAR MANTENIMIENTO

PRUEBA_MANTENIMIENTO.ACTUALIZARFecha('PRUEBA MANTENIMEINTO ACTUALIZAR FECHA', cod_mantenimiento, '01-01-2019', TRUE);
PRUEBA_MANTENIMIENTO.ACTUALIZARRevision('PRUEBA MANTENIMIENTO ACTUALIZAR REVISION', cod_mantenimiento, '01-01-2591',TRUE);

--ACTUALIZAR HORARIO

PRUEBA_HORARIO.ACTUALIZARInicio('PRUEBA HORARIO ACTUALIZAR INICIO', cod_horario, '21-1-2019', TRUE);
PRUEBA_HORARIO.ACTUALIZARFin('PRUEBA HORARIO ACTUALIZAR FIN', cod_horario, '21-1-2019',TRUE);

--ACTUALIZAR GUARDIA

PRUEBA_GUARDIA.ACTUALIZARFechaInicio('PRUEBA GUARDIA ACTUALIZAR INICIO', cod_guardia, '22-01-2019', TRUE);
PRUEBA_GUARDIA.ACTUALIZARFechaFin('PRUEBA GUARDIA ACTUALIZAR FIN', cod_guardia, '23-01-2019', TRUE);

--ACTUALIZAR FACTURA

PRUEBA_FACTURA.ACTUALIZARFecha('PRUEBA FACTURA ACTUALIZAR FECHA',cod_factura, '01-01-2019', TRUE);
PRUEBA_FACTURA.ACTUALIZAR('PRUEBA FACTURA ACTUALIZAR FECHA',cod_factura, 500, TRUE);

--ACTUALIZAR GARANTIA

PRUEBA_GARANTIA.ACTUALIZARFechaInicial('PRUEBA GARANTIA ACTUALIZAR FECHA INICIAL:', cod_garantia, '01-01-2019', TRUE);
PRUEBA_GARANTIA.ACTUALIZARFechaFinal('PRUEBA GARANTIA ACTUALIZAR FECHA FIN:', cod_garantia, '31-12-2020', TRUE);



--ELIMIAR CLIENTE

PRUEBA_CLIENTE.ELIMINAR('PRUEBA CLIENTE ELIMINAR CLIENTE', cod_cli_pepito, TRUE);


 
 
--ELIMIAR TRABAJADOR

PRUEBA_TRABAJADOR.ELIMINAR('PRUEBA TRABAJADOR ELIMINAR TRABAJADOR', cod_tra_juanito, TRUE);

--ELIMINAR VALORACIONCLIENTE

PRUEBA_VALORACIONCLIENTE.ELIMINAR('PRUEBA VALORACION CLIENTE ELIMINAR', cod_nota,TRUE);

--ELIMINAR SUGERENCIAS

PRUEBA_SUGERENCIAS.ELIMINAR('PRUEBA SUGERENCIAS ELIMINAR',cod_sugerencias, TRUE);

--ELIMINAR HORARIO

PRUEBA_HORARIO.ELIMINAR('PRUEBA HORARIO ELIMINAR',cod_horario, TRUE);

--ELIMINAR GUARDIA

PRUEBA_GUARDIA.ELIMINAR('PRUEBA GUARDIA ELIMINAR', cod_guardia, TRUE);

--ELIMINAR MANTENIMIENTO

PRUEBA_MANTENIMIENTO.ELIMINAR('PRUEBA MANTENIMIENTO ELIMINAR', cod_mantenimiento, TRUE);

--ELIMINAR FACTURA

PRUEBA_FACTURA.ELIMINAR('PRUEBA FACTURA ELIMINAR', cod_factura, TRUE);

--ELIMINAR GARANTIA

PRUEBA_GARANTIA.ELIMINAR('PRUEBA GARANTIA ELIMINAR', cod_garantia, TRUE);


END;
