-- SECUENCIAS

DROP SEQUENCE SEC_MANTENIMIENTO;
DROP SEQUENCE SEC_FACTURA;
DROP SEQUENCE SEC_GARANTIA;
DROP SEQUENCE SEC_CLIENTE;
DROP SEQUENCE SEC_VALORACIONCLIENTE;
DROP SEQUENCE SEC_TRABAJADOR;
DROP SEQUENCE SEC_GUARDIA;
DROP SEQUENCE SEC_HORARIO;
DROP SEQUENCE SEC_SUGERENCIAS;

CREATE SEQUENCE SEC_MANTENIMIENTO MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_FACTURA MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_GARANTIA MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_CLIENTE MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_VALORACIONCLIENTE MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_TRABAJADOR MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_GUARDIA MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_HORARIO MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE SEQUENCE SEC_SUGERENCIAS MINVALUE 1 MAXVALUE 9999999999
INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

--TRIGGERS ASOCIADOS A SECUENCIAS

--MANTENIMIENTO

CREATE OR REPLACE TRIGGER crear_IdMantenimiento
BEFORE INSERT ON Mantenimiento
FOR EACH ROW 
BEGIN
SELECT SEC_MANTENIMIENTO.NEXTVAL into :NEW.IdMantenimiento FROM DUAL;
END;
/

--FACTURA

CREATE OR REPLACE TRIGGER crear_IdFactura
BEFORE INSERT ON Factura
FOR EACH ROW 
BEGIN
SELECT SEC_FACTURA.NEXTVAL into :NEW.IdFactura FROM DUAL;
END;
/

--GARANTIA

CREATE OR REPLACE TRIGGER crear_IdGarantia
BEFORE INSERT ON Garantia
FOR EACH ROW 
BEGIN
SELECT SEC_GARANTIA.NEXTVAL into :NEW.IdGarantia FROM DUAL;
END;
/

--CLIENTE

CREATE OR REPLACE TRIGGER crear_IdCliente
BEFORE INSERT ON Cliente
FOR EACH ROW
BEGIN
SELECT SEC_CLIENTE.NEXTVAL into :NEW.IdCliente FROM DUAL;
END;
/

--VALORACION CLIENTE 

CREATE OR REPLACE TRIGGER crear_IdValoracionCliente
BEFORE INSERT ON ValoracionCliente
FOR EACH ROW
BEGIN
SELECT SEC_VALORACIONCLIENTE.NEXTVAL into :NEW.IdValoracionCliente FROM DUAL;
end;
/

--TRABAJADOR 

CREATE OR REPLACE TRIGGER crear_IdTrabajador
BEFORE INSERT ON Trabajador
FOR EACH ROW
BEGIN
SELECT SEC_TRABAJADOR.NEXTVAL into :NEW.IdTrabajador FROM DUAL;
end;
/

--GUARDIA

CREATE OR REPLACE TRIGGER crear_IdGuardia
BEFORE INSERT ON Guardia
FOR EACH ROW
BEGIN
SELECT SEC_GUARDIA.NEXTVAL into :NEW.IdGuardia FROM DUAL;
end;
/

--HORARIO

CREATE OR REPLACE TRIGGER crear_IdHorario
BEFORE INSERT ON Horario
FOR EACH ROW
BEGIN
SELECT SEC_HORARIO.NEXTVAL into :NEW.IdHorario FROM DUAL;
end;
/

--SUGERENCIAS

CREATE OR REPLACE TRIGGER crear_IdSugerencias
BEFORE INSERT ON Sugerencias
FOR EACH ROW
BEGIN
SELECT SEC_SUGERENCIAS.NEXTVAL into :NEW.IdSugerencias FROM DUAL;
end;
/