
--CRAECIÓN DE TABLAS

CREATE TABLE TRABAJADOR
    (IdTrabajador NUMBER(10) NOT NULL PRIMARY KEY,
    Dni VARCHAR2(10) NOT NULL,
    Nombre VARCHAR2(50) NOT NULL,
    Apellidos VARCHAR2(50) NOT NULL,
    Domicilio VARCHAR2(50) NOT NULL,
    Email VARCHAR2(50) NOT NULL,
    Contra VARCHAR2(20) NOT NULL,
    Telefono VARCHAR(9) NOT NULL);
    

CREATE TABLE HORARIO
    (IdHorario NUMBER(10) NOT NULL PRIMARY KEY,
    Dias VARCHAR2(50) NOT NULL CONSTRAINT ckdiasSemana2 CHECK(Dias IN('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo')),
    HoraInicio DATE NOT NULL,
    HoraFin DATE NOT NULL,
    FkIdTrabajador NUMBER(10) NOT NULL,
    FOREIGN KEY (FkIdTrabajador) REFERENCES TRABAJADOR ON DELETE CASCADE);
    
CREATE TABLE SUGERENCIAS
    (IdSugerencias NUMBER(10) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR2(999) NOT NULL,
    FechaDescripcion TIMESTAMP (0) NOT NULL ENABLE, 
    FkIdTrabajador NUMBER(10) NOT NULL,
    FOREIGN KEY (FkIdTrabajador) REFERENCES TRABAJADOR ON DELETE CASCADE);  


CREATE TABLE GUARDIA
    (IdGuardia NUMBER(10) NOT NULL PRIMARY KEY,
    Dias VARCHAR2(50) NOT NULL CONSTRAINT ckdiasSemana CHECK(Dias IN('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo')),
    FechaInicio DATE NOT NULL,
    FechaFin DATE NOT NULL,
    FkIdTrabajador NUMBER(10) NOT NULL,
    FOREIGN KEY (FkIdTrabajador) REFERENCES TRABAJADOR ON DELETE CASCADE);

CREATE TABLE CLIENTE 
    (IdCliente NUMBER(10) NOT NULL PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Dni VARCHAR2(10) NOT NULL,
    Apellidos VARCHAR2(50) NOT NULL,
    Direccion VARCHAR2(50) NOT NULL,
    Contra VARCHAR2(20) NOT NULL,
    Telefono VARCHAR2(9) NOT NULL);

    
CREATE TABLE VALORACIONCLIENTE
    (IdValoracionCliente NUMBER(10) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR2(999) NOT NULL,
    Nota INT NOT NULL CONSTRAINT ckNota CHECK (Nota >=1 AND Nota <=10),
    FkIdCliente NUMBER(10) NOT NULL,
    FechaDescripcion TIMESTAMP (0) NOT NULL, 
    FOREIGN KEY (FkIdCliente) REFERENCES CLIENTE ON DELETE CASCADE);

CREATE TABLE MANTENIMIENTO
    (IdMantenimiento NUMBER(10) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR2(999) NOT NULL,
    FechaProximaRevision DATE NOT NULL,
    Fecha DATE NOT NULL,
    Tipo VARCHAR2(50) NOT NULL CONSTRAINT ckTipo CHECK(Tipo IN('NORMAL', 'URGENTE')),
    FkIdTrabajador NUMBER(10) NOT NULL,
    FkIdCliente NUMBER(10) NOT NULL,
    FOREIGN KEY (FkIdCliente) REFERENCES CLIENTE ON DELETE CASCADE,
    FOREIGN KEY (FkIdTrabajador) REFERENCES TRABAJADOR ON DELETE CASCADE);
    
CREATE TABLE FACTURA
    (IdFactura NUMBER(10) NOT NULL PRIMARY KEY,
    Cantidad FLOAT NOT NULL CONSTRAINT ckCantidad CHECK( Cantidad >0),
    FechaEmision DATE NOT NULL,
    Descripcion VARCHAR2(999) NOT NULL,
    FkIdMantenimiento NUMBER(10) NOT NULL,
    FOREIGN KEY (FkIdMantenimiento) REFERENCES MANTENIMIENTO ON DELETE CASCADE);
    
CREATE TABLE GARANTIA
    (IdGarantia NUMBER(10) NOT NULL PRIMARY KEY,
    FechaInicio DATE NOT NULL, --Esta fecha debe ser igual que la de mantenimiento
    FechaFin DATE NOT NULL,
    FkIdMantenimiento NUMBER(10) NOT NULL,
    FOREIGN KEY (FkIdMantenimiento) REFERENCES MANTENIMIENTO ON DELETE CASCADE);
    
    